print("*************************")
print("The ultimate program....")
print("Loads of print statements with no variables or anything...")
print("STICK MAN")
print("     __     ")
print("    (\'-\')     ")
print("    -\\|/-     ")
print("    | | |  ")
print("     ./\\.     ")
print("*************************")